Add type checking to precommit hook when models have changed
growthbook/growthbook pull request #1341
Opened 2023-06-07 19:51 UTC by bttf

2023-06-07 22:06 UTC, tinahollygb requested changes
I don't think this is doing what #1340 says. My understanding of the ticket criteria is we should do the following **on CI**:

- run `yarn generate-api-types`
- run `git status --porcelain` 
- fail CI if it is not clean

The changes you've added will only add another task to the pre-commit hooks. This doesn't actually solve our problem because the current problem is not everybody is actually running the pre-commit hooks and the rest of us only find out after we've pulled main and modify relevant files, causing `yarn generate-api-types` to run since we are running the pre-commit hooks.

2023-06-07 23:15 UTC, bttf commented
@tinahollygb Thanks - I don't think the problem stemmed from people avoiding the pre-commit hooks but rather our pre-commit hooks not catching model changes, which would lead to these out-of-sync states. This issue wouldn't reveal itself until someone else later ran the generate command. In any case, adding to the CI flow would add another measure to prevent this from happening so I made those changes and tested.

2023-06-08 17:18 UTC, bttf commented
@jdorn @tinahollygb I believe this is ready for re-review ... Thanks!

2023-06-09 18:16 UTC, tinahollygb commented
> Thanks - I don't think the problem stemmed from people avoiding the pre-commit hooks but rather our pre-commit hooks not catching model changes, which would lead to these out-of-sync states.

@bttf it's both actually. There's multiple concerns: people not running the hooks, and also the changes your PR initially covers. You'll see on main currently if you make a random JS change and commit it, if you have pre-commit hooks enabled, lint will run and you'll commit some unrelated changes due to the latest changes in one of the components. I see the new changes you made should hopefully catch that, assuming file changes from the lint task will carry through to the task you added.

2023-06-09 18:17 UTC, tinahollygb commented on .github/workflows/ci.yml
> +          [[ -n $(git status --porcelain) ]] && echo "You need to run yarn generate-api-types" && exit 1 || true
Assuming it'll catch lint tasks above, maybe let's change the message to include `or yarn lint`

2023-06-09 18:18 UTC, tinahollygb approved these changes
Suggested copy change that might lead to developer confusion. Alternatively we can change the lint task that runs on CI to not perform any fixes (that's how I usually do it).

2023-06-09 21:04 UTC, bttf commented
@tinahollygb Thanks for the suggestion. I altered our CI workflow to run our lint command without `--fix` as you suggested (cc @jdorn). Will merge if there are no remaining concerns!

2023-06-20 21:03 UTC, merged