Bug fix 2938
growthbook/growthbook pull request #2964
Opened 2024-09-09 17:58 UTC by madhuchavva

### Features and Changes

- Add FallbackAttribute field to the Override rule. 
- Reported Bug: https://github.com/growthbook/growthbook/issues/2938

- Closes **(add link to issue here)**

### Dependencies

### Testing

### Screenshots

2024-09-09 18:02 UTC, Kevin-Chant requested changes
The actual change looks simple, but I think you'll need to fix up the diff to the unrelated files first

2024-09-09 18:20 UTC, madhuchavva commented on docker-compose.yml
> +      - "27017:27017"
Makes it easier for anyone trying to access local mongo docker instance.

2024-09-09 18:21 UTC, madhuchavva commented on packages/shared/test/util/features.test.ts
> +      error: "Unexpected token ( in JSON at position 1",
Thought so. Wanted to check with Bryce if these are needed at all.

2024-09-09 18:36 UTC, madhuchavva commented
Removed fallback attribute from percentage rollout and force value rules as the sticky bucketing is not supported.

2024-09-09 18:53 UTC, madhuchavva commented on packages/shared/test/util/features.test.ts
> +      error: "Unexpected token ( in JSON at position 1",
Reverted.

2024-09-09 18:55 UTC, Kevin-Chant approved these changes

2024-09-10 17:49 UTC, madhuchavva commented on docker-compose.yml
> +      - "27017:27017"
reverted.

2024-09-10 18:38 UTC, bryce-fitzsimons approved these changes

2024-09-10 18:59 UTC, merged