Bandits & Experiments UI fast follows (v.2 of many?)
growthbook/growthbook pull request #3145
Opened 2024-10-18 23:22 UTC by bryce-fitzsimons

- New FF rule modal modal
- FF rule layout & button changes
- general UI fixes

2024-10-19 17:31 UTC, lukesonnet requested changes
Some comments below, but most feedback and bug reported in Slack.

2024-10-20 04:13 UTC, bryce-fitzsimons commented on packages/back-end/src/validators/features.ts
> +    banditBurnInUnit: z.enum(["hours", "days"]).optional(),
This is the validator for the experiment's POST event, but does not actually reflect what will be saved into the rule model. I agree, this is not great, but not sure I want to rewire all this within this PR.

2024-10-20 04:16 UTC, bryce-fitzsimons commented on packages/stats/gbstats/bayesian/bandits.py
> +        enough_data = self.current_sample_size >= min_n
I think Luke Smith added this commit to my branch but might be good to double check...

2024-10-20 04:16 UTC, bryce-fitzsimons commented on packages/front-end/components/Archetype/AssignmentTester.tsx
> +                Rules:{" "}
I think I got all of the tsc ones...

2024-10-21 15:15 UTC, lukesonnet reviewed
resolving some comments, will do some testing later today of the new flow.

2024-10-21 15:15 UTC, lukesonnet commented on packages/stats/gbstats/bayesian/bandits.py
> +        enough_data = self.current_sample_size >= min_n
Oh shoot. Yeah I was happy to merge that to main but I see he had the base branch as yours here. That's great, thanks.

2024-10-21 15:15 UTC, lukesonnet commented on packages/back-end/src/validators/features.ts
> +    banditBurnInUnit: z.enum(["hours", "days"]).optional(),
Ok, thanks for explaining.

2024-10-22 16:02 UTC, lukesonnet approved these changes

2024-10-22 17:56 UTC, merged