Created C# docs page
growthbook/growthbook pull request #762
Opened 2022-11-28 13:59 UTC by sandi-inforit

### Features and Changes

Just added a new page with the documentation for the C# package.
Took it from the package repository and added a few tweaks to have it in line with the other documentation pages

2022-11-28 15:25 UTC, jdorn requested changes
Thanks for contributing this!  I added a couple small comments.  You can test the docs locally by doing:

```
cd docs
yarn install
yarn dev
```

Then, go to http://localhost:3200 to view once it's done building

2022-11-28 15:25 UTC, jdorn commented on docs/docs/lib/csharp.mdx
> +slug: C#
This URL slug is invalid

```suggestion
slug: c-sharp
```

2022-11-28 15:25 UTC, jdorn commented on docs/docs/lib/csharp.mdx
> +sidebar_label: C#
To make this show up in the sidebar, you also have to edit `sidebars.js` and add this to the array on line 100.

In addition, on `docs/lib/index.mdx`, there is a link to the C# github repo.  We should probably change that to point to this new page instead.

2022-11-28 15:25 UTC, jdorn commented on docs/docs/lib/csharp.mdx
> +```csharp
To make this highlighting work, we need to add `"csharp"` to the `additionalLanguages` array in `docusaurus.config.js` on line 136

2022-12-07 12:44 UTC, pascal89 reviewed
I'd suggest to apply the requested changes. Also I'd like to suggest to read the [CODE_OF_CONDUCT.md](https://github.com/growthbook/growthbook/blob/main/CODE_OF_CONDUCT.md) and the [CONTRIBUTING.md](https://github.com/growthbook/growthbook/blob/main/CONTRIBUTING.md) before you contribute to an open source project ;-) 

@maintainer this PR would close this issue: https://github.com/growthbook/growthbook-c-sharp/issues/2

2022-12-07 12:44 UTC, pascal89 commented on docs/docs/lib/csharp.mdx
> +        {
Your indenting is off, should be like this:
```cshap
    var staticFeatures = new Dictionary<string, Feature>
    {
        { "firstFeature", new Feature { DefaultValue = true }},
        { "secondFeature", new Feature { DefaultValue = false }}
    };
```

2022-12-09 17:58 UTC, Auz approved these changes

2022-12-09 18:00 UTC, merged