[WIP] [stats] Refactor SqlIntegration and stats package to use sums
growthbook/growthbook pull request #841
Opened 2022-12-15 00:14 UTC by lukesonnet

WIP PR that changes `ExperimentMetricQueryResponse` to contain sums, sums of squares, and makes a few other changes. Heavily WIP and this PR is used for some discussion.

- [ ] Write up motivation for refactor and basic design
- [ ] Update MixPanel and Google Analytics to use new interface
- [ ] Review other places where `MetricStats` is now broken
- [ ] Add tests for the `variance` and `mean` methods in for different `Statistic` objects in python library
- [ ] Add tests for ratio statistics
- [ ] Add screenshots showing prod/dev experiment results unchanged for for {binomial, count, ratio, ratio with ratio, activation, and with converted users only}

2023-01-31 16:06 UTC, jdorn requested changes

2023-01-31 16:43 UTC, lukesonnet commented on packages/back-end/src/integrations/Mixpanel.ts
> +                sum_squares: number | null;
Thank you. That whole `reduce` statement is a bit unclear to me. Perhaps we can discuss it briefly.

2023-01-31 16:45 UTC, lukesonnet commented on packages/back-end/src/integrations/Mixpanel.ts
> +              sum_squares: row.value[i].sum_squares,
Yes, thank you. I'm correct that `row.value[i]` should be the output from `mixpanel.reducer.numeric_summary('value.m${i}')`, right?

2023-01-31 16:52 UTC, lukesonnet commented on packages/back-end/src/integrations/SqlIntegration.ts
> +            COALESCE(SUM(POWER(value, 2)), 0) as main_sum_squares
I'm not sure, but I think there's no reason not to have `COALESCE(X, 0)` throughout this section so I'm going to add it back in just to be safe.

2023-02-16 16:44 UTC, lukesonnet commented on packages/back-end/src/integrations/SqlIntegration.ts
> +        ...(row.denominator_metric_type && {
@jdorn this is where I added the filter to remove unnecessary fields from returning in the UI if the metric is only a mean metric and not a ratio metric. See this loom for the updated, desired behavior: https://www.loom.com/share/da580ba3b0c543878f5e155c70e1183a

2023-02-17 21:08 UTC, jdorn submitted a review, later dismissed

2023-02-17 21:14 UTC, jdorn approved these changes

2023-02-17 21:17 UTC, jdorn approved these changes

2023-02-17 21:38 UTC, merged